/** Ledger Light design: the task board loads bounded cursor pages so growing campaigns stay responsive without hiding additional eligible work. */
import { requireUser } from "../auth.js";
import { api } from "../api.js";
import { $, $$, currency, escapeHtml, formatDate, setLoading } from "../utils.js";
import { mountNavbar } from "../components/navbar.js";
import { taskCard } from "../components/task-card.js";
import { openModal } from "../components/modal.js";
import { toast } from "../components/toast.js";
import { filterTasks } from "../testing/behavior-contracts.js";

const root = $("#tasks-root");
let allTasks = []; let nextCursor = null; let selectedCategory = ""; let selectedDevice = "";
function showTask(task) { const steps = Array.isArray(task.steps) ? task.steps : []; openModal({ title: escapeHtml(task.title), content: `<section class="task-detail"><p class="eyebrow">${escapeHtml(task.category || "Task")} · ${escapeHtml(task.provider || "Earnivo")}</p><p>${escapeHtml(task.description || "")}</p><dl><div><dt>Reward</dt><dd>${currency(task.reward)}</dd></div><div><dt>Campaign budget</dt><dd>${currency(task.maximumReward || task.reward)}</dd></div><div><dt>Expires</dt><dd>${formatDate(task.expiryDate)}</dd></div><div><dt>Proof</dt><dd>${task.requiresProof ? "Required" : "Not required"}</dd></div></dl><h3>Steps</h3><ol class="task-steps">${steps.map((step) => `<li>${escapeHtml(step)}</li>`).join("") || "<li>Review all instructions before beginning.</li>"}</ol>${task.proofInstructions ? `<p><strong>Proof instructions:</strong> ${escapeHtml(task.proofInstructions)}</p>` : ""}</section>`, actions: [{ label: "Cancel", className: "button button--secondary" }, { label: "Start task →", onClick: async (_dialog, button) => { try { setLoading(button, true, "Starting…"); const result = await api.post(`/v1/tasks/${encodeURIComponent(task.id)}/start`, {}); toast("Task started. Its record is now in your ongoing tasks.", "success"); if (result.startUrl) window.open(result.startUrl, "_blank", "noopener,noreferrer"); } catch (error) { toast(error.message, "error"); return false; } finally { setLoading(button, false); } } }] }); }
function filteredTasks() { return filterTasks(allTasks, { category: selectedCategory, device: selectedDevice }); }
function renderTasks() { const tasks = filteredTasks(); root.className = ""; root.innerHTML = `<section class="page-heading"><div><p class="eyebrow">Task board</p><h1>Find work that fits.</h1><p>Only active tasks for which you are eligible are shown here.</p></div></section><section class="filter-bar"><div class="category-ribbon" data-categories><button class="${!selectedCategory ? "is-active" : ""}" data-category="">All tasks</button>${[...new Set(allTasks.map((task) => task.category).filter(Boolean))].map((category) => `<button class="${selectedCategory === category ? "is-active" : ""}" data-category="${escapeHtml(category)}">${escapeHtml(category)}</button>`).join("")}</div><label><span class="sr-only">Filter by device</span><select data-device-filter><option value="">Any device</option><option value="mobile" ${selectedDevice === "mobile" ? "selected" : ""}>Mobile</option><option value="desktop" ${selectedDevice === "desktop" ? "selected" : ""}>Desktop</option><option value="tablet" ${selectedDevice === "tablet" ? "selected" : ""}>Tablet</option></select></label></section>${tasks.length ? `<section class="task-grid">${tasks.map(taskCard).join("")}</section>` : `<section class="empty-state"><h2>No matching tasks.</h2><p>Try another category or device filter. Tasks appear only while active and eligible.</p></section>`}${nextCursor ? `<div class="pagination-action"><button class="button button--secondary" data-load-more>Load more eligible tasks</button></div>` : ""}`; $$('[data-open-task]', root).forEach((button) => button.addEventListener("click", () => showTask(allTasks.find((task) => task.id === button.dataset.openTask)))); $$('[data-category]', root).forEach((button) => button.addEventListener("click", () => { selectedCategory = button.dataset.category; renderTasks(); })); $("[data-device-filter]", root).addEventListener("change", (event) => { selectedDevice = event.target.value; renderTasks(); }); $("[data-load-more]", root)?.addEventListener("click", loadMore); }
async function loadMore(event) { const button = event.currentTarget; try { setLoading(button, true, "Loading…"); const response = await api.get(`/v1/tasks?cursor=${encodeURIComponent(nextCursor)}&limit=20`); allTasks = [...allTasks, ...(response.items || [])]; nextCursor = response.nextCursor || null; renderTasks(); } catch (error) { toast(error.message, "error"); setLoading(button, false); } }
async function init() { try { const user = await requireUser(); if (!user) return; await mountNavbar("tasks"); const response = await api.get("/v1/tasks?limit=20"); allTasks = response.items || []; nextCursor = response.nextCursor || null; renderTasks(); } catch (error) { root.className = "empty-state"; root.innerHTML = `<h2>The task board is unavailable.</h2><p>${escapeHtml(error.message)}</p>`; } }
init();
