/** Withdrawal policy derives only from platform settings; the daily counter reserves requested value atomically. */
import { HttpError } from "./http.js";

export function normalisePayoutMethod(value) { return String(value || "").trim().toLowerCase().slice(0, 40); }
export function normalisePayoutReference(value) { const reference = String(value || "").trim().slice(0, 500); if (reference.length < 3 || /[\u0000-\u001F]/.test(reference)) throw new HttpError(400, "Provide a valid payout reference of at least three characters.", "invalid_payout_reference"); return reference; }
const cleanDetail = (value, length = 200) => String(value || "").trim().replace(/[\u0000-\u001F]/g, "").slice(0, length);
const formatINR = (amount) => `₹${Number(amount || 0).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
export function withdrawalPayoutDetails(method, input = {}) { if (["bank", "bank_transfer"].includes(method)) { const accountNumber = cleanDetail(input.accountNumber, 80); const ifscCode = cleanDetail(input.ifscCode, 20).toUpperCase(); if (!accountNumber) throw new HttpError(400, "Account number is required for a bank withdrawal.", "bank_account_required"); if (!ifscCode) throw new HttpError(400, "IFSC code is required for a bank withdrawal.", "bank_ifsc_required"); return { accountNumber, ifscCode }; } if (method === "upi") { const upiId = cleanDetail(input.upiId, 120); if (!upiId) throw new HttpError(400, "UPI ID is required for a UPI withdrawal.", "upi_id_required"); return { upiId }; } if (method === "gift_card") { const giftCardType = cleanDetail(input.giftCardType, 80); const giftCardDeliveryMethod = cleanDetail(input.giftCardDeliveryMethod, 20).toLowerCase(); const giftCardDeliveryValue = cleanDetail(input.giftCardDeliveryValue, 300); if (!giftCardType) throw new HttpError(400, "Gift card type is required for a gift card withdrawal.", "gift_card_type_required"); if (!giftCardDeliveryMethod) { const legacyDetails = cleanDetail(input.giftCardDetails, 300); if (legacyDetails) return { giftCardType, giftCardDeliveryMethod: "legacy", giftCardDeliveryValue: legacyDetails, giftCardDetails: legacyDetails }; throw new HttpError(400, "Choose email or contact delivery for a gift card withdrawal.", "gift_card_delivery_method_required"); } if (!["email", "contact"].includes(giftCardDeliveryMethod)) throw new HttpError(400, "Gift card delivery must use email or contact.", "invalid_gift_card_delivery_method"); if (!giftCardDeliveryValue) throw new HttpError(400, "Gift card delivery details are required.", "gift_card_delivery_value_required"); return { giftCardType, giftCardDeliveryMethod, giftCardDeliveryValue, giftCardDetails: giftCardDeliveryValue }; } return {}; }
export function withdrawalPolicy(settings = {}) { const minimumAmount = Math.max(0, Number(settings.minimumWithdrawal || 0)); const dailyAmountLimit = Math.max(0, Number(settings.dailyWithdrawalLimit || 0)); const enabledMethods = [...new Set((Array.isArray(settings.enabledPayoutMethods) ? settings.enabledPayoutMethods : []).map(normalisePayoutMethod).filter(Boolean))]; return { minimumAmount, dailyAmountLimit, enabledMethods }; }
export function withdrawalDay(timestamp = new Date().toISOString()) { return new Date(timestamp).toISOString().slice(0, 10); }
export function withdrawalDailyCounterId(userId, day) { return `withdrawal_${userId}_${day}`; }
export function assertWithdrawalPolicy(policy, { method, amount, dailyReservedAmount = 0 }) { if (amount < policy.minimumAmount) throw new HttpError(400, `The minimum withdrawal is ${formatINR(policy.minimumAmount)}.`, "withdrawal_below_minimum"); if (policy.enabledMethods.length && !policy.enabledMethods.includes(method)) throw new HttpError(400, "This payout method is not currently enabled.", "payout_method_disabled"); if (policy.dailyAmountLimit && dailyReservedAmount + amount > policy.dailyAmountLimit) throw new HttpError(409, "The daily withdrawal limit has been reached.", "daily_withdrawal_limit_reached"); }
