/** Dedicated campaign counter helpers provide one atomic source of truth for capacity and reward-budget reservations. */
const activeStatuses = new Set(["in_progress", "verification"]);
const numberOrNull = (value) => Number.isFinite(Number(value)) && Number(value) >= 0 ? Number(value) : null;

export const campaignCounterId = (taskId) => `campaign_${taskId}`;
export function campaignLimit(task = {}) { const limit = Number(task.campaignLimit ?? task.userLimit ?? 0); return Number.isInteger(limit) && limit > 0 ? limit : 0; }
export function campaignRewardBudget(task = {}) { const budget = Number(task.maximumReward || 0); return Number.isFinite(budget) && budget > 0 ? budget : 0; }

export function submissionCounts(taskId, submissions = []) { return submissions.reduce((counts, entry) => { if (entry.taskId !== taskId) return counts; if (entry.status === "completed") counts.completed += 1; if (activeStatuses.has(entry.status)) counts.reserved += 1; return counts; }, { completed: 0, reserved: 0 }); }
export function rewardHistory(taskId, submissions = []) { return submissions.reduce((totals, entry) => { if (entry.taskId !== taskId) return totals; const reward = Number(entry.reward || 0); if (entry.status === "completed") totals.paid += reward; if (activeStatuses.has(entry.status)) totals.reserved += reward; return totals; }, { paid: 0, reserved: 0 }); }

export function campaignCounterSeed(task, submissions = []) { const counts = submissionCounts(task.id, submissions); const rewards = rewardHistory(task.id, submissions); return { taskId: task.id, completedCount: counts.completed, reservedCount: counts.reserved, paidRewardTotal: rewards.paid, reservedRewardTotal: rewards.reserved }; }
export function counterState(task, counter, submissions = []) { if (!counter) return { ...task, ...campaignCounterSeed(task, submissions) }; const { id: _counterDocumentId, ...counterFields } = counter; return { ...task, ...counterFields }; }
export function campaignCounts(task, submissions = []) { const fallback = submissionCounts(task.id, submissions); return { completed: numberOrNull(task.completedCount) ?? fallback.completed, reserved: numberOrNull(task.reservedCount) ?? fallback.reserved, legacyCompleted: numberOrNull(task.completedCount) === null, legacyReserved: numberOrNull(task.reservedCount) === null }; }
export function campaignRewardTotals(task, submissions = []) { const fallback = rewardHistory(task.id, submissions); return { paid: numberOrNull(task.paidRewardTotal) ?? fallback.paid, reserved: numberOrNull(task.reservedRewardTotal) ?? fallback.reserved, legacyPaid: numberOrNull(task.paidRewardTotal) === null, legacyReserved: numberOrNull(task.reservedRewardTotal) === null }; }
export function canReserveCampaignSlot(task, submissions = []) { const limit = campaignLimit(task); const counts = campaignCounts(task, submissions); return !limit || counts.completed + counts.reserved < limit; }
export function canCompleteCampaignSlot(task, submissions = []) { const limit = campaignLimit(task); const counts = campaignCounts(task, submissions); return !limit || counts.completed < limit; }
export function canReserveRewardBudget(task, submissions = [], reward = 0) { const budget = campaignRewardBudget(task); const totals = campaignRewardTotals(task, submissions); return !budget || totals.paid + totals.reserved + Number(reward || 0) <= budget; }
export function canSpendRewardBudget(task, submissions = [], reward = 0) { const budget = campaignRewardBudget(task); const totals = campaignRewardTotals(task, submissions); return !budget || totals.paid + Number(reward || 0) <= budget; }
export function campaignCounterIncrements(task, submissions, { completed = 0, reserved = 0 } = {}) { const counts = campaignCounts(task, submissions); return { completedCount: counts.legacyCompleted ? Math.max(0, counts.completed + completed) : completed, reservedCount: counts.legacyReserved ? Math.max(0, counts.reserved + reserved) : reserved }; }
export function rewardBudgetIncrements(task, submissions, { paid = 0, reserved = 0 } = {}) { const totals = campaignRewardTotals(task, submissions); return { paidRewardTotal: totals.legacyPaid ? Math.max(0, totals.paid + paid) : paid, reservedRewardTotal: totals.legacyReserved ? Math.max(0, totals.reserved + reserved) : reserved }; }
export function applyCounterChanges(seed, changes) { return { completedCount: seed.completedCount + changes.completedCount, reservedCount: seed.reservedCount + changes.reservedCount, paidRewardTotal: seed.paidRewardTotal + changes.paidRewardTotal, reservedRewardTotal: seed.reservedRewardTotal + changes.reservedRewardTotal }; }
