/** Provider postbacks require HMAC, freshness, provider validation, and an atomically created providerTransactions ledger entry before exactly-once processing. */
import { HttpError } from "./http.js";
import { getDocument, writeCreate } from "./firestore.js";
import { markSubmissionForVerification, approveSubmission, rejectSubmission } from "./reward.js";

const encoder = new TextEncoder();
const bytesToHex = (bytes) => [...new Uint8Array(bytes)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
const fixedTimeEqual = (left, right) => { if (left.length !== right.length) return false; let result = 0; for (let index = 0; index < left.length; index += 1) result |= left.charCodeAt(index) ^ right.charCodeAt(index); return result === 0; };
export const providerTransactionId = (transactionId) => { const value = String(transactionId || "").trim(); if (!/^[A-Za-z0-9._-]{1,180}$/.test(value)) throw new HttpError(400, "Provider transaction ID contains unsupported characters.", "invalid_provider_transaction_id"); return value; };
export const providerTransactionLedgerId = (providerId, transactionId) => `${providerTransactionId(providerId)}__${providerTransactionId(transactionId)}`;
export const terminalPostbackStatuses = Object.freeze(["approved", "rejected", "cancelled", "reversed"]);
function required(value, name) { const output = typeof value === "string" ? value.trim() : ""; if (!output) throw new HttpError(400, `${name} is required.`, "invalid_postback"); return output; }
function postbackSecret(env, providerId) { try { const secrets = JSON.parse(env.PROVIDER_HMAC_SECRETS || "{}"); if (typeof secrets?.[providerId] === "string" && secrets[providerId]) return secrets[providerId]; } catch { throw new HttpError(500, "Provider signing secret configuration is invalid.", "provider_secret_configuration_error"); } if (env.POSTBACK_HMAC_SECRET) return env.POSTBACK_HMAC_SECRET; throw new HttpError(500, "Provider postback signing is not configured.", "postback_signing_not_configured"); }
export async function hmacSignature(secret, timestamp, rawBody) { const key = await crypto.subtle.importKey("raw", encoder.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); return bytesToHex(await crypto.subtle.sign("HMAC", key, encoder.encode(`${timestamp}.${rawBody}`))); }
export function validateTimestamp(value, nowMs = Date.now(), maxAgeSeconds = 300) { const seconds = Number(value); if (!Number.isInteger(seconds)) throw new HttpError(401, "Postback timestamp is invalid.", "invalid_postback_timestamp"); if (Math.abs(nowMs - seconds * 1000) > maxAgeSeconds * 1000) throw new HttpError(401, "Postback timestamp is outside the accepted window.", "stale_postback"); return seconds; }
export async function processPostback(request, env, payload, rawBody) {
  const providerId = providerTransactionId(required(payload.providerId, "Provider ID")); const transactionId = providerTransactionId(required(payload.transactionId, "Provider transaction ID")); const ledgerId = providerTransactionLedgerId(providerId, transactionId); const submissionId = required(payload.submissionId, "Submission ID"); const taskId = required(payload.taskId, "Task ID"); const status = required(payload.status, "Postback status").toLowerCase(); if (!["verification", ...terminalPostbackStatuses].includes(status)) throw new HttpError(400, "Postback status is invalid.", "invalid_postback");
  const timestamp = request.headers.get("X-Postback-Timestamp"); validateTimestamp(timestamp, Date.now(), Math.min(Math.max(Number(env.POSTBACK_MAX_AGE_SECONDS) || 300, 30), 3600)); const signature = (request.headers.get("X-Postback-Signature") || "").replace(/^sha256=/i, "").toLowerCase(); const expected = await hmacSignature(postbackSecret(env, providerId), timestamp, rawBody); if (!fixedTimeEqual(signature, expected)) throw new HttpError(401, "Postback signature verification failed.", "invalid_postback_signature");
  const existingTransaction = await getDocument(env, "providerTransactions", ledgerId); if (existingTransaction) { if (existingTransaction.provider !== providerId || existingTransaction.submissionId !== submissionId || existingTransaction.taskId !== taskId || existingTransaction.status !== status) throw new HttpError(409, "Provider transaction identity conflicts with an existing terminal record.", "provider_transaction_conflict"); return { idempotent: true, alreadyProcessed: true, providerTransactionId: transactionId, status: existingTransaction.status, submissionId: existingTransaction.submissionId }; }
  const [provider, submission] = await Promise.all([getDocument(env, "providers", providerId), getDocument(env, "submissions", submissionId)]); if (!provider || provider.status !== "active") throw new HttpError(403, "Provider is not active for postbacks.", "provider_not_active"); if (!submission || submission.taskId !== taskId) throw new HttpError(404, "The postback submission and campaign do not match.", "submission_campaign_mismatch"); const task = await getDocument(env, "tasks", taskId); if (!task || task.provider !== provider.id) throw new HttpError(403, "The provider is not authorized for this campaign.", "provider_campaign_mismatch");
  const recordedAt = new Date().toISOString(); const transactionWrite = writeCreate(env, "providerTransactions", ledgerId, { ledgerId, providerTransactionId: transactionId, provider: providerId, submissionId, taskId, status, reward: Number(submission.reward || 0), receivedAt: recordedAt, timestamp: Number(timestamp) }); const details = { proof: payload.proof || null, providerReference: transactionId };
  if (status === "verification") { if (submission.status === "verification") return { idempotent: true, alreadyProcessed: true, submissionId: submission.id, status: "verification" }; if (submission.status !== "in_progress") throw new HttpError(409, "The provider verification callback does not match the submission’s current state.", "invalid_submission_status"); return markSubmissionForVerification(env, submission.id, `provider:${providerId}`, details); }
  const verified = submission.status === "in_progress" ? await markSubmissionForVerification(env, submission.id, `provider:${providerId}`, details) : submission; if (verified.status !== "verification") throw new HttpError(409, "The provider postback does not match the submission’s current state.", "invalid_submission_status"); return status === "approved" ? approveSubmission(env, verified.id, `provider:${providerId}`, { extraWrites: [transactionWrite] }) : rejectSubmission(env, verified.id, `provider:${providerId}`, payload.reason, { extraWrites: [transactionWrite] });
}
