/** Reward decisions atomically settle task totals, campaign counters, daily counters, wallets, notifications, and submissions. */
import { HttpError } from "./http.js";
import { commit, getDocument, listCollection, setDocument, writeCreate, writeDelete, writeIncrement, writePatch } from "./firestore.js";
import { applyCounterChanges, campaignCounterId, campaignCounterIncrements, campaignCounterSeed, canCompleteCampaignSlot, canSpendRewardBudget, counterState, rewardBudgetIncrements } from "./campaign.js";
import { canRecordDailyCompletion, dailyCompletionLimit, dailyCounterId, utcDay } from "./daily.js";
import { qualifyReferral } from "./referral.js";

const submissionLockId = (submission) => `${submission.userId}_${submission.taskId}`;
async function requireWallet(env, userId) { let wallet = await getDocument(env, "wallets", userId); if (!wallet) { await setDocument(env, "wallets", userId, { userId, availableBalance: 0, pendingWithdrawalAmount: 0, verificationAmount: 0, createdAt: new Date().toISOString() }); wallet = await getDocument(env, "wallets", userId); } return wallet; }
async function campaignWithCounter(env, taskId) { const [task, counter] = await Promise.all([getDocument(env, "tasks", taskId), getDocument(env, "campaignCounters", campaignCounterId(taskId))]); if (!task) throw new HttpError(409, "The campaign is no longer available.", "campaign_not_found"); const submissions = counter ? [] : await listCollection(env, "submissions", 500); return { task, counter, seed: counter ? null : campaignCounterSeed(task, submissions), state: counterState(task, counter, submissions) }; }
function counterWrite(env, campaign, changes, timestamp) { if (campaign.counter) return writeIncrement(env, "campaignCounters", campaign.counter.id, changes, { updateTime: campaign.counter.updatedAt }); const fields = { taskId: campaign.task.id, ...applyCounterChanges(campaign.seed, changes), createdAt: timestamp, updatedAt: timestamp }; return writeCreate(env, "campaignCounters", campaignCounterId(campaign.task.id), fields); }

export async function markSubmissionForVerification(env, submissionId, actorId, { proof = null, providerReference = null, extraWrites = [] } = {}) { const submission = await getDocument(env, "submissions", submissionId); if (!submission) throw new HttpError(404, "The submission was not found.", "submission_not_found"); if (submission.status !== "in_progress") throw new HttpError(409, "Only an in-progress submission can be sent for verification.", "invalid_submission_status"); if (submission.requiresProof && !String(proof || "").trim()) throw new HttpError(400, "Proof is required before this submission can be reviewed.", "proof_required"); const wallet = await requireWallet(env, submission.userId); const timestamp = new Date().toISOString(); const amount = Number(submission.reward || 0); await commit(env, [writePatch(env, "submissions", submissionId, { status: "verification", proof: proof || null, providerReference: providerReference || null, completedAt: timestamp, submittedAt: timestamp, submittedBy: actorId }, { updateTime: submission.updatedAt }), writeIncrement(env, "wallets", submission.userId, { verificationAmount: amount }, { updateTime: wallet.updatedAt }), writeDelete(env, "activeSubmissions", submissionLockId(submission)), ...extraWrites]); return { ...submission, status: "verification", completedAt: timestamp }; }

export async function approveSubmission(env, submissionId, adminId, { extraWrites = [] } = {}) {
  const submission = await getDocument(env, "submissions", submissionId); if (!submission) throw new HttpError(404, "The submission was not found.", "submission_not_found"); if (submission.status !== "verification") throw new HttpError(409, "Only a verification submission can be approved.", "invalid_submission_status");
  const [wallet, campaign] = await Promise.all([requireWallet(env, submission.userId), campaignWithCounter(env, submission.taskId)]); const amount = Number(submission.reward || 0);
  if (!canCompleteCampaignSlot(campaign.state)) throw new HttpError(409, "The campaign completion cap has already been reached.", "campaign_limit_reached");
  if (!canSpendRewardBudget(campaign.state, [], amount)) throw new HttpError(409, "The campaign reward budget has already been reached.", "maximum_reward_reached");
  const timestamp = new Date().toISOString(); const day = utcDay(timestamp); const dailyId = dailyCounterId(campaign.task.id, day); const dailyRecord = await getDocument(env, "campaignDailyStats", dailyId); if (!canRecordDailyCompletion(campaign.task, dailyRecord)) throw new HttpError(409, "The campaign daily completion cap has already been reached.", "daily_limit_reached"); const referral = await qualifyReferral(env, submission.userId, timestamp);
  const changes = { ...campaignCounterIncrements(campaign.state, [], { completed: 1, reserved: -1 }), ...rewardBudgetIncrements(campaign.state, [], { paid: amount, reserved: -amount }) }; const transactionId = crypto.randomUUID(); const dailyWrite = dailyCompletionLimit(campaign.task) ? (dailyRecord ? writeIncrement(env, "campaignDailyStats", dailyId, { completedCount: 1 }, { updateTime: dailyRecord.updatedAt }) : writeCreate(env, "campaignDailyStats", dailyId, { taskId: campaign.task.id, day, completedCount: 1, createdAt: timestamp, updatedAt: timestamp })) : null;
  await commit(env, [writePatch(env, "submissions", submissionId, { status: "completed", completedAt: timestamp, reviewedAt: timestamp, reviewedBy: adminId, rejectionReason: null }, { updateTime: submission.updatedAt }), writeIncrement(env, "wallets", submission.userId, { availableBalance: amount, verificationAmount: -amount }, { updateTime: wallet.updatedAt }), writeIncrement(env, "tasks", campaign.task.id, { completions: 1 }, { updateTime: campaign.task.updatedAt }), counterWrite(env, campaign, changes, timestamp), ...(dailyWrite ? [dailyWrite] : []), ...referral.writes, writeCreate(env, "transactions", transactionId, { userId: submission.userId, type: "reward", reference: submissionId, amount, status: "completed", createdAt: timestamp }), writeCreate(env, "notifications", `submission_approved_${submissionId}`, { userId: submission.userId, category: "task", title: "Task approved", body: `Your submission for ${submission.taskTitle || "this task"} was approved.`, unread: true, readAt: null, createdAt: timestamp }), ...extraWrites]);
  return { ...submission, status: "completed", completedAt: timestamp };
}

export async function rejectSubmission(env, submissionId, adminId, reason, { extraWrites = [] } = {}) { const submission = await getDocument(env, "submissions", submissionId); if (!submission) throw new HttpError(404, "The submission was not found.", "submission_not_found"); if (submission.status !== "verification") throw new HttpError(409, "Only a verification submission can be rejected.", "invalid_submission_status"); const [wallet, campaign] = await Promise.all([requireWallet(env, submission.userId), campaignWithCounter(env, submission.taskId)]); const timestamp = new Date().toISOString(); const amount = Number(submission.reward || 0); const rejectionReason = reason || "The task requirements were not met."; const changes = { ...campaignCounterIncrements(campaign.state, [], { reserved: -1 }), ...rewardBudgetIncrements(campaign.state, [], { reserved: -amount }) }; await commit(env, [writePatch(env, "submissions", submissionId, { status: "failed", reviewedAt: timestamp, reviewedBy: adminId, rejectionReason }, { updateTime: submission.updatedAt }), writeIncrement(env, "wallets", submission.userId, { verificationAmount: -amount }, { updateTime: wallet.updatedAt }), counterWrite(env, campaign, changes, timestamp), writeCreate(env, "notifications", `submission_failed_${submissionId}`, { userId: submission.userId, category: "task", title: "Task not approved", body: rejectionReason, unread: true, readAt: null, createdAt: timestamp }), ...extraWrites]); return { ...submission, status: "failed", rejectionReason }; }
