/** Ledger Light admin: provider metadata is explicit so task origins and postback expectations remain reviewable. */
import { requireAdmin } from "./admin-auth.js";
import { adminApi } from "./admin-api.js";
import { mountAdminNav } from "./admin-nav.js";
import { $, escapeHtml, setLoading, statusClass } from "../../js/utils.js";
import { openModal } from "../../js/components/modal.js";
import { toast } from "../../js/components/toast.js";
const root = $("#admin-root");
function editor(provider) { return openModal({ title: provider ? "Edit provider" : "Add provider", content: `<form id="provider-form" class="admin-form-grid"><label>Name<input name="name" required value="${escapeHtml(provider?.name || "")}"/></label><label>Integration<select name="integration"><option value="standard" ${(provider?.integration || "standard") === "standard" ? "selected" : ""}>Standard provider</option><option value="cpalead" ${provider?.integration === "cpalead" ? "selected" : ""}>CPalead (official setup required)</option></select></label><label>Status<select name="status"><option value="active" ${provider?.status === "active" ? "selected" : ""}>active</option><option value="disabled" ${provider?.status !== "active" ? "selected" : ""}>disabled</option></select></label><label class="full">Postback notes<textarea name="postbackNotes" rows="4" placeholder="Use official CPAlead credentials and postback details only after approval.">${escapeHtml(provider?.postbackNotes || "")}</textarea></label><p class="field-note full">CPalead remains disabled until an administrator completes the official account setup and explicitly changes its status to active.</p></form>`, actions: [{ label: "Cancel", className: "button button--secondary" }, { label: "Save provider", onClick: async (_dialog, button) => { const form = $("#provider-form"); if (!form.reportValidity()) return false; try { setLoading(button, true, "Saving…"); const body = Object.fromEntries(new FormData(form)); if (!provider && body.integration === "cpalead" && body.status === "active") body.status = "disabled"; if (provider) await adminApi.update("providers", provider.id, body); else await adminApi.create("providers", body); toast("Provider saved.", "success"); init(); } catch (error) { toast(error.message, "error"); return false; } finally { setLoading(button, false); } } }] }); }
async function init() { try { if (!await requireAdmin()) return; mountAdminNav("providers"); const { items = [] } = await adminApi.list("providers"); root.className = ""; root.innerHTML = `<section class="admin-heading"><div><p class="eyebrow">Providers</p><h1>Task sources.</h1><p>Maintain only providers whose reward, postback, and task terms can be reviewed.</p></div><button class="button button--primary" data-create>Add provider <span>→</span></button></section><div class="table-wrap"><table><thead><tr><th>Name</th><th>Integration</th><th>Status</th><th>Postback notes</th><th></th></tr></thead><tbody>${items.map((item) => `<tr><td><strong>${escapeHtml(item.name)}</strong></td><td>${escapeHtml(item.integration || "standard")}</td><td><span class="${statusClass(item.status)}">${escapeHtml(item.status || "active")}</span></td><td>${escapeHtml(item.postbackNotes || "—")}</td><td class="admin-action-row"><button data-edit="${item.id}">Edit</button><button class="danger" data-delete="${item.id}">Delete</button></td></tr>`).join("") || "<tr><td colspan='5'>No providers have been configured.</td></tr>"}</tbody></table></div>`; $("[data-create]", root).addEventListener("click", () => editor()); root.querySelectorAll("[data-edit]").forEach((button) => button.addEventListener("click", () => editor(items.find((item) => item.id === button.dataset.edit)))); root.querySelectorAll("[data-delete]").forEach((button) => button.addEventListener("click", async () => { if (!confirm("Delete this provider record?")) return; try { await adminApi.remove("providers", button.dataset.delete); toast("Provider deleted.", "success"); init(); } catch (error) { toast(error.message, "error"); } })); } catch (error) { root.className = "empty-state"; root.innerHTML = `<h2>Providers could not be loaded.</h2><p>${escapeHtml(error.message)}</p>`; } }
init();
