/** Ledger Light admin: a settings-read failure is blocking, never treated as an empty configuration. */
import { requireAdmin } from "./admin-auth.js";
import { adminApi } from "./admin-api.js";
import { mountAdminNav } from "./admin-nav.js";
import { $, escapeHtml, setLoading } from "../../js/utils.js";
import { toast } from "../../js/components/toast.js";
import { buildSettingsPayload, settingsLoadState } from "../../js/testing/behavior-contracts.js";

const root = $("#admin-root");
const formMarkup = (settings, { newConfiguration = false } = {}) => `<section class="admin-heading"><div><p class="eyebrow">Platform settings</p><h1>Configuration record.</h1><p>Update country, referral, and withdrawal policies in a reviewable document.</p></div></section>${newConfiguration ? `<div class="configuration-callout"><strong>No platform settings record exists yet.</strong><p>Saving this form creates the first configuration record.</p></div>` : ""}<section class="admin-record-card"><form id="settings-form" class="admin-form-grid"><label class="full">Supported countries (JSON array of objects with code and name)<textarea name="countries" rows="5">${escapeHtml(JSON.stringify(settings.supportedCountries || [], null, 2))}</textarea><small>Codes must use two-letter ISO-style values, such as IN or US.</small></label><label>Minimum withdrawal<input name="minimumWithdrawal" type="number" min="0" step="0.01" value="${escapeHtml(settings.minimumWithdrawal || "0")}"/></label><label>Daily withdrawal limit<input name="dailyWithdrawalLimit" type="number" min="0" step="0.01" value="${escapeHtml(settings.dailyWithdrawalLimit || "0")}"/><small>Use 0 for no amount cap.</small></label><label class="full">Enabled payout methods (comma-separated)<input name="enabledPayoutMethods" maxlength="300" value="${escapeHtml((settings.enabledPayoutMethods || []).join(", "))}" placeholder="upi, bank_transfer"/><small>Members receive only these methods in the withdrawal form.</small></label><label class="full">Referral qualifying rule<textarea name="referralQualifyingRule" rows="3">${escapeHtml(settings.referralQualifyingRule || "Complete and receive approval for the configured number of tasks.")}</textarea></label><label>Approved tasks required<select name="referralQualifyingCompletedTasks"><option value="1" ${Number(settings.referralQualifyingCompletedTasks || 1) === 1 ? "selected" : ""}>1 approved task</option><option value="2" ${Number(settings.referralQualifyingCompletedTasks) === 2 ? "selected" : ""}>2 approved tasks</option><option value="3" ${Number(settings.referralQualifyingCompletedTasks) === 3 ? "selected" : ""}>3 approved tasks</option></select></label><label>Referrer reward<input name="referralReward" type="number" min="0" step="0.01" value="${escapeHtml(settings.referralReward || "0")}"/><small>Credited exactly once after qualification. Use 0 to track verification without a reward.</small></label><div class="full"><button class="button button--primary" type="submit">Save configuration <span>→</span></button></div></form></section>`;
async function init() { try { if (!await requireAdmin()) return; mountAdminNav("settings"); let settings = {}; let newConfiguration = false; try { settings = await adminApi.get("settings", "platform"); } catch (error) { const state = settingsLoadState(error); if (state === "create") newConfiguration = true; else { root.className = "empty-state"; root.innerHTML = `<h2>Could not load current platform settings.</h2><p>${escapeHtml(error.message)} No changes have been applied. Check access and try again.</p><button class="button button--secondary" data-retry>Retry</button>`; $("[data-retry]", root).addEventListener("click", init); return; } } root.className = ""; root.innerHTML = formMarkup(settings, { newConfiguration }); $("#settings-form", root).addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget, button = $("button", form); try { const countries = JSON.parse(form.countries.value || "[]"); if (!Array.isArray(countries)) throw new Error("Supported countries must be a JSON array."); const referralReward = Number(form.referralReward.value || 0), minimumWithdrawal = Number(form.minimumWithdrawal.value || 0), dailyWithdrawalLimit = Number(form.dailyWithdrawalLimit.value || 0); if (![referralReward, minimumWithdrawal, dailyWithdrawalLimit].every((value) => Number.isFinite(value) && value >= 0)) throw new Error("Reward and withdrawal settings must be zero or greater."); setLoading(button, true, "Saving…"); await adminApi.update("settings", "platform", buildSettingsPayload({ supportedCountries: countries, referralQualifyingRule: form.referralQualifyingRule.value, referralQualifyingCompletedTasks: Number(form.referralQualifyingCompletedTasks.value), referralReward, minimumWithdrawal, dailyWithdrawalLimit, enabledPayoutMethods: form.enabledPayoutMethods.value })); toast("Platform configuration saved.", "success"); } catch (error) { toast(error.message, "error"); } finally { setLoading(button, false); } }); } catch (error) { root.className = "empty-state"; root.innerHTML = `<h2>Settings could not be loaded.</h2><p>${escapeHtml(error.message)}</p>`; } }
init();
