/** Ledger Light admin: submissions receive a documented approval or rejection, never an untracked balance change. */
import { requireAdmin } from "./admin-auth.js";
import { adminApi } from "./admin-api.js";
import { mountAdminNav } from "./admin-nav.js";
import { $, currency, escapeHtml, formatDate, statusClass } from "../../js/utils.js";
import { openModal } from "../../js/components/modal.js";
import { toast } from "../../js/components/toast.js";
import { adminSubmissionDecision } from "../../js/testing/behavior-contracts.js";
const root = $("#admin-root");
async function decide(id, action) { if (action === "reject") { const dialog = openModal({ title: "Reject submission", content: `<label>Reason<textarea id="reject-reason" rows="4" placeholder="State the unmet requirement clearly."></textarea></label>`, actions: [{ label: "Cancel", className: "button button--secondary" }, { label: "Reject", className: "button button--primary", onClick: async () => { try { const request = adminSubmissionDecision(id, "reject", $("#reject-reason", dialog).value); await adminApi.action(request.resource, request.id, request.action, request.payload); toast("Submission rejected and recorded.", "success"); init(); } catch (error) { toast(error.message, "error"); return false; } } }] }); return; } try { const request = adminSubmissionDecision(id, "approve"); await adminApi.action(request.resource, request.id, request.action); toast("Submission approved and reward credited.", "success"); init(); } catch (error) { toast(error.message, "error"); } }
async function init() { try { if (!await requireAdmin()) return; mountAdminNav("submissions"); const { items = [] } = await adminApi.list("submissions"); root.className = ""; root.innerHTML = `<section class="admin-heading"><div><p class="eyebrow">Submissions</p><h1>Verification queue.</h1><p>Approve only when the task conditions and submitted proof support completion.</p></div></section><div class="table-wrap"><table><thead><tr><th>Task</th><th>User</th><th>Provider</th><th>Started</th><th>Reward</th><th>Status</th><th></th></tr></thead><tbody>${items.map((item) => `<tr><td><strong>${escapeHtml(item.taskTitle || item.taskId)}</strong></td><td>${escapeHtml(item.userId)}</td><td>${escapeHtml(item.provider || "—")}</td><td>${formatDate(item.startedAt)}</td><td>${currency(item.reward)}</td><td><span class="${statusClass(item.status)}">${escapeHtml(item.status)}</span></td><td class="admin-action-row">${item.status === "verification" ? `<button data-approve="${item.id}">Approve</button><button class="danger" data-reject="${item.id}">Reject</button>` : item.status === "in_progress" ? "Waiting for member" : "Reviewed"}</td></tr>`).join("") || "<tr><td colspan='7'>No submissions have been received.</td></tr>"}</tbody></table></div>`; root.querySelectorAll("[data-approve]").forEach((button) => button.addEventListener("click", () => decide(button.dataset.approve, "approve"))); root.querySelectorAll("[data-reject]").forEach((button) => button.addEventListener("click", () => decide(button.dataset.reject, "reject"))); } catch (error) { root.className = "empty-state"; root.innerHTML = `<h2>Submission records could not be loaded.</h2><p>${escapeHtml(error.message)}</p>`; } }
init();
