/** Ledger Light admin: approval records review only; paid is a separate, provider-referenced operational confirmation. */
import { requireAdmin } from "./admin-auth.js";
import { adminApi } from "./admin-api.js";
import { mountAdminNav } from "./admin-nav.js";
import { $, currency, escapeHtml, formatDate, setLoading, statusClass } from "../../js/utils.js";
import { openModal } from "../../js/components/modal.js";
import { toast } from "../../js/components/toast.js";

const root = $("#admin-root");
function actionCopy(action) { return action === "approve" ? { title: "Approve for payout", body: "This confirms the request passed review. It does not confirm money was sent.", label: "Approve for payout", note: "Approval note (optional)" } : action === "paid" ? { title: "Confirm payout sent", body: "Only use this after the external payout has actually been completed. Record the provider reference for reconciliation.", label: "Mark as paid", note: "Payout provider reference", required: true } : { title: "Reject withdrawal", body: "Explain why the request is being rejected. The held amount will return to the member’s available balance.", label: "Reject request", note: "Rejection reason", required: true, danger: true }; }
function resolve(id, action) { const copy = actionCopy(action); openModal({ title: copy.title, content: `<p>${copy.body}</p><label class="stacked-label">${copy.note}<textarea id="withdrawal-note" rows="4" ${copy.required ? "required" : ""} placeholder="Record the review outcome clearly."></textarea></label>${action === "paid" ? `<label class="stacked-label">Optional payout note<textarea id="withdrawal-extra-note" rows="3" placeholder="Optional operational note."></textarea></label>` : ""}`, actions: [{ label: "Cancel", className: "button button--secondary" }, { label: copy.label, className: copy.danger ? "button button--secondary" : "button button--primary", onClick: async (dialog, button) => { const note = $("#withdrawal-note", dialog).value.trim(); const extraNote = $("#withdrawal-extra-note", dialog)?.value.trim() || ""; if (copy.required && !note) { toast("Complete the required operational record before continuing.", "error"); return false; } try { setLoading(button, true, "Recording…"); await adminApi.action("withdrawals", id, action, action === "paid" ? { paymentReference: note, note: extraNote } : { note }); toast(action === "paid" ? "Withdrawal marked as paid." : `Withdrawal ${action}d.`, "success"); await init(); } catch (error) { toast(error.message, "error"); return false; } finally { setLoading(button, false); } } }] }); }
async function init() { try { if (!await requireAdmin()) return; mountAdminNav("withdrawals"); const { items = [] } = await adminApi.list("withdrawals"); root.className = ""; root.innerHTML = `<section class="admin-heading"><div><p class="eyebrow">Withdrawals</p><h1>Payment requests.</h1><p>Approval is a review decision. Mark a request as paid only after the actual payout has been completed and referenced.</p></div></section><div class="table-wrap"><table><thead><tr><th>User</th><th>Amount</th><th>Method</th><th>Reference</th><th>Requested</th><th>Status</th><th></th></tr></thead><tbody>${items.map((item) => `<tr><td>${escapeHtml(item.userId)}</td><td><strong>${currency(item.amount)}</strong></td><td>${escapeHtml(item.method)}</td><td>${escapeHtml(item.payoutReference)}</td><td>${formatDate(item.createdAt)}</td><td><span class="${statusClass(item.status)}">${escapeHtml(item.status)}</span></td><td class="admin-action-row">${item.status === "pending" ? `<button data-approve="${item.id}">Approve</button><button class="danger" data-reject="${item.id}">Reject</button>` : item.status === "approved" ? `<button data-paid="${item.id}">Mark paid</button>` : item.status === "paid" ? "Payout confirmed" : "Rejected"}</td></tr>`).join("") || "<tr><td colspan='7'>No withdrawal requests have been made.</td></tr>"}</tbody></table></div>`; root.querySelectorAll("[data-approve]").forEach((button) => button.addEventListener("click", () => resolve(button.dataset.approve, "approve"))); root.querySelectorAll("[data-reject]").forEach((button) => button.addEventListener("click", () => resolve(button.dataset.reject, "reject"))); root.querySelectorAll("[data-paid]").forEach((button) => button.addEventListener("click", () => resolve(button.dataset.paid, "paid"))); } catch (error) { root.className = "empty-state"; root.innerHTML = `<h2>Withdrawal records could not be loaded.</h2><p>${escapeHtml(error.message)}</p>`; } }
init();

