import assert from "node:assert/strict";
import test from "node:test";
import { detectRequestDevice, isDeviceEligible, normaliseCompatibility } from "../src/eligibility.js";
import { unreadNotificationCountQuery } from "../src/notifications.js";
import { normaliseOptionalHttpsDestination } from "../src/task-validation.js";
import { assertWithdrawalPolicy, normalisePayoutReference, withdrawalDailyCounterId, withdrawalDay, withdrawalPayoutDetails, withdrawalPolicy } from "../src/withdrawal-policy.js";

test("tablet device classes remain server-enforced alongside mobile and desktop", () => { const tablet = new Request("https://worker.test", { headers: { "User-Agent": "Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X)" } }); assert.equal(detectRequestDevice(tablet), "tablet"); assert.deepEqual(normaliseCompatibility(["mobile", "tablet", "tablet"]), ["mobile", "tablet"]); assert.equal(isDeviceEligible({ deviceCompatibility: ["tablet"] }, {}, tablet), true); assert.equal(isDeviceEligible({ deviceCompatibility: ["desktop"] }, {}, tablet), false); });
test("optional task destinations permit blank values but reject non-HTTPS values when provided", () => { assert.equal(normaliseOptionalHttpsDestination(""), ""); assert.equal(normaliseOptionalHttpsDestination("https://offers.example/a"), "https://offers.example/a"); assert.throws(() => normaliseOptionalHttpsDestination("http://offers.example"), { code: "invalid_task_destination" }); });
test("unread notifications use a direct recipient and unread-state aggregation query", () => { assert.deepEqual(unreadNotificationCountQuery("member-4"), { filters: [{ field: "userId", value: "member-4" }, { field: "unread", value: true }] }); });
test("withdrawal policy enforces configured minimum, enabled methods, and daily amount limits", () => { const policy = withdrawalPolicy({ minimumWithdrawal: 50, dailyWithdrawalLimit: 250, enabledPayoutMethods: ["UPI", "bank_transfer"] }); assert.deepEqual(policy.enabledMethods, ["upi", "bank_transfer"]); assert.doesNotThrow(() => assertWithdrawalPolicy(policy, { method: "upi", amount: 100, dailyReservedAmount: 100 })); assert.throws(() => assertWithdrawalPolicy(policy, { method: "upi", amount: 25, dailyReservedAmount: 0 }), { code: "withdrawal_below_minimum" }); assert.throws(() => assertWithdrawalPolicy(policy, { method: "wallet", amount: 100, dailyReservedAmount: 0 }), { code: "payout_method_disabled" }); assert.throws(() => assertWithdrawalPolicy(policy, { method: "upi", amount: 200, dailyReservedAmount: 100 }), { code: "daily_withdrawal_limit_reached" }); assert.equal(normalisePayoutReference("  UPI@member  "), "UPI@member"); assert.equal(withdrawalDay("2026-08-25T12:00:00.000Z"), "2026-08-25"); assert.equal(withdrawalDailyCounterId("member-4", "2026-08-25"), "withdrawal_member-4_2026-08-25"); });
test("Bank, UPI, and Gift Card withdrawal details are required and preserved for the existing request payload", () => { assert.deepEqual(withdrawalPayoutDetails("bank", { accountNumber: "00011234", ifscCode: "hdfc0001" }), { accountNumber: "00011234", ifscCode: "HDFC0001" }); assert.throws(() => withdrawalPayoutDetails("bank", { accountNumber: "00011234" }), { code: "bank_ifsc_required" }); assert.deepEqual(withdrawalPayoutDetails("upi", { upiId: "member@upi" }), { upiId: "member@upi" }); assert.throws(() => withdrawalPayoutDetails("upi", {}), { code: "upi_id_required" }); assert.deepEqual(withdrawalPayoutDetails("gift_card", { giftCardType: "myntra", giftCardDeliveryMethod: "email", giftCardDeliveryValue: "member@example.test" }), { giftCardType: "myntra", giftCardDeliveryMethod: "email", giftCardDeliveryValue: "member@example.test", giftCardDetails: "member@example.test" }); assert.throws(() => withdrawalPayoutDetails("gift_card", { giftCardType: "amazon", giftCardDeliveryMethod: "contact" }), { code: "gift_card_delivery_value_required" }); });
