import assert from "node:assert/strict";
import test from "node:test";
import { activeProviderOptions, adminSubmissionDecision, adminTaskLifecycleAction, apiErrorMessage, buildSettingsPayload, filterTasks, loginRedirectPath, notificationReadPath, payoutMethodOptions, safeNextPath, settingsLoadState, shouldCloseModal, shouldRollbackSignup, signupBootstrapPayload, taskEditPayload, withdrawalFormErrors } from "../../js/testing/behavior-contracts.js";

test("login and administrator redirects preserve safe next paths only", () => { assert.equal(safeNextPath("/pages/wallet.html?tab=history"), "/pages/wallet.html?tab=history"); assert.equal(safeNextPath("https://unsafe.example"), "/pages/home.html"); assert.equal(loginRedirectPath("/pages/tasks.html"), "/pages/login.html?next=%2Fpages%2Ftasks.html"); assert.equal(loginRedirectPath("/pages/home.html", { admin: true }), "/pages/login.html?next=%2Fadmin%2Findex.html"); });
test("signup referral bootstrap preserves a trimmed referral code and rolls back only newly created signup accounts", () => { assert.deepEqual(signupBootstrapPayload({ email: "member@example.test", referralCode: " REF-7 " }), { email: "member@example.test", referralCode: "REF-7" }); assert.equal(shouldRollbackSignup("signup", { uid: "member-1" }), true); assert.equal(shouldRollbackSignup("login", { uid: "member-1" }), false); });
test("task filtering supports category, device, all-device, and search criteria", () => { const tasks = [{ title: "Quick survey", provider: "Pulse", category: "Survey", deviceCompatibility: ["mobile"] }, { title: "Desktop study", provider: "ResearchCo", category: "Study", deviceCompatibility: ["all"] }]; assert.deepEqual(filterTasks(tasks, { category: "Survey", device: "mobile" }), [tasks[0]]); assert.deepEqual(filterTasks(tasks, { device: "desktop", search: "research" }), [tasks[1]]); });
test("withdrawal form behavior validates balance, minimum, method, and payout reference", () => { assert.deepEqual(withdrawalFormErrors({ amount: 100, availableBalance: 200, minimumWithdrawal: 50, method: "upi", payoutReference: "member@upi" }), []); assert.equal(withdrawalFormErrors({ amount: 25, availableBalance: 20, minimumWithdrawal: 50, method: "", payoutReference: "x" }).length, 4); assert.deepEqual(payoutMethodOptions(["bank_transfer", "upi"]), [{ value: "bank_transfer", label: "Bank Transfer" }, { value: "upi", label: "Upi" }]); });
test("notification read, modal outcomes, and admin review decisions use constrained UI contracts", () => { assert.equal(notificationReadPath("notice/7"), "/v1/notifications/notice%2F7/read"); assert.equal(shouldCloseModal(false), false); assert.equal(shouldCloseModal(undefined), true); assert.deepEqual(adminSubmissionDecision("sub-1", "approve"), { resource: "submissions", id: "sub-1", action: "approve", payload: undefined }); assert.deepEqual(adminSubmissionDecision("sub-1", "reject", "  proof missing "), { resource: "submissions", id: "sub-1", action: "reject", payload: { reason: "proof missing" } }); });
test("task edit and hide actions keep the non-destructive administrator route contract", () => { assert.deepEqual(taskEditPayload({ country: " in ", reward: "10", maximumReward: "100", userLimit: "25", dailyLimit: "5" }), { country: "IN", reward: 10, maximumReward: 100, userLimit: 25, dailyLimit: 5 }); assert.deepEqual(adminTaskLifecycleAction("task-7", "hidden"), { resource: "tasks", id: "task-7", action: "status", payload: { status: "hidden" } }); });
test("task editors expose only active provider IDs instead of accepting ambiguous names", () => { assert.deepEqual(activeProviderOptions([{ id: "provider-a", name: "CashMudra", status: "active" }, { id: "provider-b", name: "Old provider", status: "disabled" }]), [{ value: "provider-a", label: "CashMudra" }]); });
test("settings and API errors normalize values into user-safe controller results", () => { assert.deepEqual(buildSettingsPayload({ minimumWithdrawal: "50", dailyWithdrawalLimit: "500", enabledPayoutMethods: "upi, bank_transfer" }), { minimumWithdrawal: 50, dailyWithdrawalLimit: 500, enabledPayoutMethods: ["upi", "bank_transfer"] }); assert.equal(settingsLoadState(null), "ready"); assert.equal(settingsLoadState({ code: "settings_not_found" }), "create"); assert.equal(settingsLoadState({ code: "firestore_error" }), "blocked"); assert.equal(apiErrorMessage({ error: { message: "Payout method is disabled." } }), "Payout method is disabled."); assert.equal(apiErrorMessage({}), "The request could not be completed."); });
